export const CHANGE_INPUT_VALUE  = "CHANGE_INPUT_VALUE";
export const SUBMIT_SERVICE_CELL      = "SUBMIT_SERVICE_CELL";
export const GET_SERVICE_CELL_LIST    = "GET_SERVICE_CELL_LIST";
export const GET_SERVICE_CELL_DETAILS = "GET_SERVICE_CELL_DETAILS";
export const UPDATE_SERVICE_CELL_DETAILS = "UPDATE_SERVICE_CELL_DETAILS";
export const DELETE_SERVICE_CELL      = "DELETE_SERVICE_CELL";